"""Curated sector coverage based on issuer business and product disclosures.

Sector membership describes a business relationship, not price momentum.
Keep the issuer source with each entry so future catalog updates are reviewable.
"""

from dataclasses import dataclass


SECTOR_CONCEPTS: dict[str, tuple[str, ...]] = {
    "pharma": ("의약", "의약품", "제약", "바이오", "제약바이오", "바이오의약품",
               "신약", "바이오시밀러", "CDMO", "biotech", "biopharma", "pharmaceutical"),
    "space": ("우주", "우주항공", "항공우주", "위성", "인공위성", "발사체", "로켓",
              "누리호", "space", "aerospace", "satellite"),
    "defense": ("방산", "방위산업", "국방", "방위", "군수", "유도무기", "defense", "defence"),
    "robotics": ("로봇", "로보틱스", "협동로봇", "휴머노이드", "산업용로봇", "로봇자동화",
                 "robot", "robotics", "humanoid", "cobot"),
    "semiconductor": ("반도체", "메모리", "HBM", "HBM3E", "HBM4", "DRAM", "NAND",
                      "파운드리", "semiconductor", "foundry"),
    "ai": ("AI", "인공지능", "생성형AI", "생성형인공지능", "AI반도체", "AI서버",
           "클라우드", "GPU", "artificial intelligence", "generative AI", "cloud"),
    "battery": ("2차전지", "이차전지", "배터리", "전기차배터리", "리튬이온", "ESS",
                "에너지저장장치", "battery", "energy storage"),
    "power": ("전력", "전력기기", "전력설비", "전력인프라", "전력망", "변압기", "송배전",
              "배전반", "전선", "스마트그리드", "power grid", "transformer", "switchgear"),
    "nuclear": ("원전", "원자력", "소형모듈원전", "SMR", "nuclear", "small modular reactor"),
    "renewable": ("신재생", "신재생에너지", "재생에너지", "태양광", "태양전지", "태양광모듈",
                  "solar", "renewable", "photovoltaic"),
    "shipbuilding": ("조선", "조선업", "조선해양", "선박", "LNG선", "LNG운반선", "해양플랜트",
                     "shipbuilding", "LNG carrier"),
}

SECTOR_LABELS = {
    "pharma": "의약·제약·바이오", "space": "우주·위성·항공우주", "defense": "방산",
    "robotics": "로봇·자동화", "semiconductor": "반도체", "ai": "인공지능·AI",
    "battery": "2차전지·배터리·ESS", "power": "전력·전력기기", "nuclear": "원전·SMR",
    "renewable": "신재생에너지·태양광", "shipbuilding": "조선·LNG선",
}


@dataclass(frozen=True)
class SectorCompany:
    symbol: str
    name: str
    market: str
    concepts: tuple[str, ...]
    business: str
    products: tuple[str, ...]
    source_url: str


SECTOR_COMPANIES: tuple[SectorCompany, ...] = (
    SectorCompany("207940", "삼성바이오로직스", "KR", ("pharma",),
        "바이오의약품의 연구·개발·위탁생산 CDMO 서비스를 제공하는 기업",
        ("항체 의약품", "세포주·공정 개발", "의약품 위탁생산"),
        "https://samsungbiologics.com/kr/services/biologics-overview"),
    SectorCompany("068270", "셀트리온", "KR", ("pharma",),
        "항체 바이오시밀러와 신약을 개발·생산·판매하는 제약바이오 기업",
        ("바이오시밀러", "항체 의약품", "신약 개발"),
        "https://www.celltrion.com/en-us"),
    SectorCompany("000100", "유한양행", "KR", ("pharma",),
        "전문의약품과 일반의약품을 개발·공급하는 제약기업",
        ("전문의약품", "일반의약품", "의료기기·진단시약"),
        "https://www.yuhan.co.kr/Products/List/"),
    SectorCompany("128940", "한미약품", "KR", ("pharma",),
        "개량·복합신약과 혁신신약을 연구개발하는 제약기업",
        ("신약", "전문의약품", "항암제"),
        "https://www.hanmi.co.kr/about/hanmi-pharm/company.hm"),
    SectorCompany("012450", "한화에어로스페이스", "KR", ("space", "defense"),
        "우주 발사체 엔진·체계종합과 항공엔진·지상 방산 장비를 공급하는 기업",
        ("누리호 발사체 엔진", "위성 추진시스템", "항공엔진", "자주포"),
        "https://www.hanwha.co.kr/business/manufacture/aerospace.do"),
    SectorCompany("047810", "한국항공우주", "KR", ("space", "defense"),
        "군용 항공기와 위성·우주 발사체 관련 체계를 개발·제작하는 항공우주 기업",
        ("군용 항공기", "위성", "발사체 조립"),
        "https://m.koreaaero.com/"),
    SectorCompany("272210", "한화시스템", "KR", ("space", "defense"),
        "방산 전자체계와 위성 탑재체·통신 등 우주·항공 솔루션을 제공하는 기업",
        ("위성 EO·IR·SAR 탑재체", "위성 통신", "항공전자"),
        "https://www.hanwhasystems.com/kr/business/defense/space.do"),
    SectorCompany("099320", "쎄트렉아이", "KR", ("space",),
        "지구관측 위성 시스템과 위성 영상 관련 사업을 수행하는 우주기업",
        ("지구관측 위성", "위성 시스템", "위성 영상"),
        "https://www.satreci.com/kr/"),
    SectorCompany("454910", "두산로보틱스", "KR", ("robotics",),
        "협동로봇과 로봇 솔루션을 개발·공급하는 기업",
        ("협동로봇", "산업용 로봇 솔루션"),
        "https://www.doosanrobotics.com/kr/about/company/overview/"),
    SectorCompany("277810", "레인보우로보틱스", "KR", ("robotics",),
        "협동로봇·모바일 로봇·휴머노이드 기반 로봇 플랫폼을 개발하는 기업",
        ("협동로봇", "모바일 휴머노이드", "사족로봇"),
        "https://rainbow-robotics.com/company/"),
    SectorCompany("005930", "삼성전자", "KR", ("semiconductor", "ai"),
        "메모리 반도체와 파운드리 사업을 영위하고 AI용 HBM을 공급하는 전자기업",
        ("DRAM", "NAND", "HBM", "파운드리"),
        "https://semiconductor.samsung.com/dram/hbm/"),
    SectorCompany("000660", "SK하이닉스", "KR", ("semiconductor", "ai"),
        "AI 시스템에 쓰이는 HBM과 DRAM·NAND 메모리 반도체를 공급하는 기업",
        ("HBM", "DRAM", "NAND", "AI 메모리"),
        "https://news.skhynix.com/en/"),
    SectorCompany("000990", "DB하이텍", "KR", ("semiconductor",),
        "아날로그·전력 반도체 등의 특화 파운드리 서비스를 제공하는 기업",
        ("반도체 파운드리", "아날로그 반도체", "전력관리 반도체"),
        "https://www.dbhitek.com/en/technology/overview"),
    SectorCompany("035420", "NAVER", "KR", ("ai",),
        "AI 기술과 클라우드 플랫폼·인공지능 서비스를 제공하는 인터넷 기업",
        ("AI 클라우드", "인공지능 서비스", "Neurocloud"),
        "https://www.navercorp.com/service/cloud"),
    SectorCompany("035720", "카카오", "KR", ("ai",),
        "인터넷 플랫폼을 바탕으로 AI 모델과 인공지능 서비스를 개발하는 기업",
        ("AI 모델", "인공지능 서비스", "생성형 AI"),
        "https://www.kakaocorp.com/page/ai?cardlist=true&type=ai"),
    SectorCompany("373220", "LG에너지솔루션", "KR", ("battery",),
        "전기차 배터리와 에너지저장장치 ESS용 배터리를 공급하는 기업",
        ("전기차 배터리", "리튬이온 배터리", "ESS 배터리"),
        "https://www.lgensol.com/kr/business/ess"),
    SectorCompany("006400", "삼성SDI", "KR", ("battery",),
        "리튬이온 이차전지와 전기차·ESS용 배터리를 개발·공급하는 기업",
        ("전기차 배터리", "ESS", "리튬이온 배터리"),
        "https://www.samsungsdi.com/business/index.html"),
    SectorCompany("267260", "HD현대일렉트릭", "KR", ("power",),
        "송배전용 변압기·차단기·배전반 등 전력기기를 공급하는 기업",
        ("변압기", "차단기", "배전반", "송배전 전력설비"),
        "https://www.hd-hyundaielectric.com/"),
    SectorCompany("010120", "LS ELECTRIC", "KR", ("power",),
        "전력 제품·시스템과 전력 계통 보호·공급 솔루션을 제공하는 기업",
        ("전력기기", "배전반", "스마트그리드", "전력망 솔루션"),
        "https://www.ls-electric.com/ko/"),
    SectorCompany("298040", "효성중공업", "KR", ("power",),
        "변압기·차단기·송배전 시스템 등 전력 인프라를 공급하는 기업",
        ("변압기", "차단기", "송배전 시스템", "ESS"),
        "https://www.hyosungheavyindustries.com/kr"),
    SectorCompany("034020", "두산에너빌리티", "KR", ("nuclear",),
        "원자력 발전 주기기와 소형모듈원전 SMR 관련 기자재를 공급하는 기업",
        ("원전 기자재", "SMR", "원자로"),
        "https://www.doosanenerbility.com/kr/business/smr_smart"),
    SectorCompany("009830", "한화솔루션", "KR", ("renewable",),
        "Qcells를 통해 태양광 셀·모듈과 신재생에너지 솔루션을 제공하는 기업",
        ("태양광 셀", "태양광 모듈", "태양광 발전 솔루션"),
        "https://www.hanwhasolutions.com/m/en/"),
    SectorCompany("042660", "한화오션", "KR", ("shipbuilding",),
        "LNG 운반선과 해양플랜트 등을 건조하는 조선해양 기업",
        ("LNG 운반선", "LNG-FPSO", "LNG-FSRU", "해양플랜트"),
        "https://www.hanwhaocean.com/pdf/Hanwha_Ocean_Brochure_KR_2025.pdf"),
    SectorCompany("010140", "삼성중공업", "KR", ("shipbuilding",),
        "LNG 운반선과 해양플랜트 등 고부가 선박을 건조하는 조선기업",
        ("LNG 운반선", "FLNG", "친환경 선박"),
        "https://samsungshi.com/En/Ps_ship.aspx"),
    SectorCompany("LLY", "Eli Lilly", "US", ("pharma",),
        "의약품을 연구개발·생산하는 글로벌 제약기업",
        ("전문의약품", "신약"), "https://www.lilly.com/lillydirect"),
    SectorCompany("AMGN", "Amgen", "US", ("pharma",),
        "바이오의약품과 신약을 연구개발하는 바이오 제약기업",
        ("바이오의약품", "신약"), "https://www.amgen.com/"),
    SectorCompany("RKLB", "Rocket Lab", "US", ("space",),
        "우주 발사 서비스와 위성·우주 시스템을 제공하는 기업",
        ("로켓 발사체", "위성 시스템", "우주 발사 서비스"),
        "https://rocketlabcorp.com/home/"),
    SectorCompany("ASTS", "AST SpaceMobile", "US", ("space",),
        "저궤도 위성 기반 모바일 통신망을 개발하는 우주 통신 기업",
        ("위성 통신망", "인공위성"), "https://ast-science.com/"),
    SectorCompany("LMT", "Lockheed Martin", "US", ("defense", "space"),
        "군용 항공기·방산 체계와 위성 등 우주 시스템을 공급하는 기업",
        ("군용 항공기", "유도무기", "위성", "우주 시스템"),
        "https://www.lockheedmartin.com/en-us/who-we-are/business-areas.html"),
    SectorCompany("TER", "Teradyne", "US", ("robotics", "semiconductor"),
        "반도체 테스트 장비와 자회사를 통한 협동로봇·모바일 로봇을 공급하는 기업",
        ("반도체 테스트", "협동로봇", "모바일 로봇"),
        "https://www.teradyne.com/robotics/"),
    SectorCompany("NVDA", "NVIDIA", "US", ("ai", "semiconductor"),
        "AI 연산과 데이터센터용 GPU·반도체 및 인공지능 플랫폼을 공급하는 기업",
        ("GPU", "AI 가속기", "AI 서버 플랫폼"),
        "https://www.nvidia.com/en-us/products/"),
    SectorCompany("AMD", "Advanced Micro Devices", "US", ("ai", "semiconductor"),
        "CPU·GPU와 데이터센터용 AI 반도체 가속기를 공급하는 기업",
        ("GPU", "AI 가속기", "서버 CPU"),
        "https://www.amd.com/en/products/accelerators/instinct.html"),
    SectorCompany("MSFT", "Microsoft", "US", ("ai",),
        "Azure 클라우드와 AI 모델·인공지능 서비스를 제공하는 소프트웨어 기업",
        ("AI 클라우드", "인공지능 서비스", "생성형 AI"),
        "https://azure.microsoft.com/en-us/products/category/ai"),
    SectorCompany("TSLA", "Tesla", "US", ("battery",),
        "전기차와 Megapack 배터리 에너지저장장치 ESS를 공급하는 기업",
        ("배터리 에너지저장장치", "ESS", "Megapack"),
        "https://www.tesla.com/utilities"),
    SectorCompany("ETN", "Eaton", "US", ("power",),
        "전력 배전·제어와 전기 인프라 등 전력관리 솔루션을 공급하는 기업",
        ("전력기기", "배전반", "전력관리 솔루션"),
        "https://www.eaton.com/us/en-us/company.html"),
    SectorCompany("SMR", "NuScale Power", "US", ("nuclear",),
        "소형모듈원전 SMR 설계·원자력 기술을 개발하는 기업",
        ("소형모듈원전", "원전 설계", "SMR"),
        "https://www.nuscalepower.com/"),
    SectorCompany("FSLR", "First Solar", "US", ("renewable",),
        "태양광 발전용 박막 태양전지 모듈을 제조하는 신재생에너지 기업",
        ("태양광 모듈", "태양전지"),
        "https://www.firstsolar.com/"),
)
